name: Ganesh
favicon: null
layout_spectrum: 0.20584247331134975
typography_spectrum: 0.5048789407592267
title: 'Architect '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaea'
    - '#0e0506'
    - '#d96518'
    - '#d49d43'
    - '#5e2410'
  brandStrength: 0.8186278846114874
  lightness: 0.8353975033387542
  saturation: 0.2741579981520772
  rhythmicContrast: 0.23841162212193012
purpose: []
