name: Ganesh
favicon: null
layout_spectrum: 0.56039
typography_spectrum: 0.26333
title: 'Ganesh Hingnekar : Architect '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaea'
    - '#0e0506'
    - '#d96518'
    - '#d49d43'
    - '#5e2410'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
